//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34003
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BibtexManager.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("texworks")]
        public string TexEditorProcName {
            get {
                return ((string)(this["TexEditorProcName"]));
            }
            set {
                this["TexEditorProcName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RecentLib {
            get {
                return ((string)(this["RecentLib"]));
            }
            set {
                this["RecentLib"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{author} ({year}). {title}. {publisher}: pp. -.")]
        public string EnglishBookItemFormat {
            get {
                return ((string)(this["EnglishBookItemFormat"]));
            }
            set {
                this["EnglishBookItemFormat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{author} ({year}). {title}. {journal}. {volume} ({number}): pp. {pages}.")]
        public string EnglishArticleItemFormat {
            get {
                return ((string)(this["EnglishArticleItemFormat"]));
            }
            set {
                this["EnglishArticleItemFormat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{author}：《{title}》，{publisher}，{year}年：第-页。")]
        public string NonEnglishBookItemFormat {
            get {
                return ((string)(this["NonEnglishBookItemFormat"]));
            }
            set {
                this["NonEnglishBookItemFormat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{author}：{title}，《{journal}》，{year}（{number}）：第{pages}页。")]
        public string NonEnglishArticleItemFormat {
            get {
                return ((string)(this["NonEnglishArticleItemFormat"]));
            }
            set {
                this["NonEnglishArticleItemFormat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("scholar.google.com/scholar?q={0}")]
        public string DefaultSearchEngine {
            get {
                return ((string)(this["DefaultSearchEngine"]));
            }
            set {
                this["DefaultSearchEngine"] = value;
            }
        }
    }
}
